import type { NetBirdSnapshot } from "@/lib/types";

export function getDemoNetBirdSnapshot(apiUrl: string): NetBirdSnapshot {
  return {
    mode: "demo",
    generatedAt: new Date().toISOString(),
    apiUrl,
    warnings: ["NETBIRD_API_TOKEN is not set. NetBird data and write results are simulated."],
    networks: [
      {
        id: "demo-network-production",
        name: "Production data plane",
        description: "Demo network for production database and service endpoints.",
        routers: ["demo-router-production"],
        resources: ["demo-resource-orders", "demo-resource-worker"],
        policies: ["demo-policy-platform"],
        routing_peers_count: 2,
      },
      {
        id: "demo-network-staging",
        name: "Staging data plane",
        description: "Demo network for pre-production validation.",
        routers: ["demo-router-staging"],
        resources: ["demo-resource-staging-db"],
        policies: ["demo-policy-engineering"],
        routing_peers_count: 1,
      },
    ],
    resources: [
      {
        id: "demo-resource-orders",
        name: "orders-primary",
        address: "orders.example.internal",
        description: "Demo RDS resource.",
        enabled: true,
        type: "domain",
        groups: [{ id: "demo-group-platform", name: "Platform" }],
        networkId: "demo-network-production",
        networkName: "Production data plane",
      },
      {
        id: "demo-resource-worker",
        name: "i-demo-worker (worker)",
        address: "worker.example.internal",
        description: "Demo EC2 resource.",
        enabled: true,
        type: "domain",
        groups: [{ id: "demo-group-platform", name: "Platform" }],
        networkId: "demo-network-production",
        networkName: "Production data plane",
      },
      {
        id: "demo-resource-staging-db",
        name: "staging-primary",
        address: "staging-db.example.internal",
        description: "Demo staging database resource.",
        enabled: true,
        type: "domain",
        groups: [{ id: "demo-group-engineering", name: "Engineering" }],
        networkId: "demo-network-staging",
        networkName: "Staging data plane",
      },
    ],
    routers: [
      {
        id: "demo-router-production",
        peer_groups: ["demo-group-routing"],
        metric: 100,
        masquerade: true,
        enabled: true,
        networkId: "demo-network-production",
        networkName: "Production data plane",
      },
      {
        id: "demo-router-staging",
        peer: "demo-peer-staging",
        metric: 200,
        masquerade: true,
        enabled: true,
        networkId: "demo-network-staging",
        networkName: "Staging data plane",
      },
    ],
    peers: [
      {
        id: "demo-peer-production",
        name: "router-production-01",
        hostname: "router-production-01",
        ip: "100.96.0.10",
        connected: true,
        os: "linux",
        version: "demo",
        user_id: "demo-user-ana",
        groups: [{ id: "demo-group-routing", name: "Network Routers" }],
      },
      {
        id: "demo-peer-staging",
        name: "router-staging-01",
        hostname: "router-staging-01",
        ip: "100.96.0.20",
        connected: true,
        os: "linux",
        version: "demo",
        user_id: "demo-user-ana",
        groups: [{ id: "demo-group-routing", name: "Network Routers" }],
      },
      {
        id: "demo-peer-offline",
        name: "router-production-02",
        hostname: "router-production-02",
        ip: "100.96.0.11",
        connected: false,
        os: "linux",
        version: "demo",
        user_id: "demo-user-ana",
        groups: [{ id: "demo-group-routing", name: "Network Routers" }],
      },
      {
        id: "demo-peer-laptop",
        name: "ana-mbp",
        hostname: "ana-mbp",
        ip: "100.96.0.41",
        connected: true,
        os: "darwin",
        version: "demo",
        user_id: "demo-user-ana",
        groups: [{ id: "demo-group-platform", name: "Platform" }],
      },
      {
        id: "demo-peer-phone",
        name: "tom-iphone",
        hostname: "tom-iphone",
        ip: "100.96.0.52",
        connected: true,
        os: "ios",
        version: "demo",
        user_id: "demo-user-tom",
        groups: [{ id: "demo-group-engineering", name: "Engineering" }],
      },
    ],
    groups: [
      { id: "demo-group-platform", name: "Platform", peers_count: 4, resources_count: 2 },
      { id: "demo-group-engineering", name: "Engineering", peers_count: 18, resources_count: 1 },
      { id: "demo-group-routing", name: "Network Routers", peers_count: 3, resources_count: 0 },
    ],
    users: [
      {
        id: "demo-user-ana",
        email: "ana@example.com",
        name: "Ana Silva",
        role: "admin",
        status: "active",
        last_login: "2026-08-03T09:12:00Z",
        auto_groups: ["demo-group-platform"],
      },
      {
        id: "demo-user-tom",
        email: "tom@example.com",
        name: "Tom Berger",
        role: "user",
        status: "active",
        last_login: "2026-08-02T18:40:00Z",
        auto_groups: ["demo-group-engineering"],
      },
      {
        id: "demo-user-invited",
        email: "new@example.com",
        name: "New Hires",
        role: "user",
        status: "invited",
      },
    ],
    policies: [
      {
        id: "demo-policy-platform",
        name: "Platform to production services",
        description: "Demo access policy.",
        enabled: true,
        rules: [{ id: "demo-rule-platform", name: "Platform access", enabled: true, action: "accept", protocol: "all" }],
      },
      {
        id: "demo-policy-engineering",
        name: "Engineering to staging",
        description: "Demo access policy.",
        enabled: true,
        rules: [{ id: "demo-rule-engineering", name: "Staging access", enabled: true, action: "accept", protocol: "all" }],
      },
    ],
  };
}
